//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos_UFLA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descricao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descricao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursos_UFLA.Descricao", typeof(Descricao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Administração
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 40
        ///Coordenador: Profª. Maria Cristina Angélico Mendonça
        ///Telefone: (35) 3829-1767
        ///E-mail: mariacam @ dae.ufla.br.
        /// </summary>
        internal static string Administracao {
            get {
                return ResourceManager.GetString("Administracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Administração Pública
        ///Regime: Semestral
        ///Período: Noturno
        ///Duração: 9 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Prof. Dênis Renato de Oliveira
        ///Telefone: (35) 3829-3130
        ///E-mail: denis.oliveira@dae.ufla.br.
        /// </summary>
        internal static string AdmPublica {
            get {
                return ResourceManager.GetString("AdmPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Engenheiro Agrícola
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 25
        ///Coordenador: Profª. Mirléia Aparecida de Carvalho
        ///Telefone: (35) 3829-1533
        ///E-mail: mirleiaap @ deg.ufla.br.
        /// </summary>
        internal static string Agricola {
            get {
                return ResourceManager.GetString("Agricola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Agronomia
        ///Regime: Semestral
        ///Período: Integral
        ///Duração:9 semestres
        ///Nº de vagas por semestre: 100
        ///Coordenador: Prof. Rafael Pio
        ///Telefone: (35) 3829-1007
        ///E-mail: rafaelpio @ dag.ufla.br.
        /// </summary>
        internal static string Agronomia {
            get {
                return ResourceManager.GetString("Agronomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Engenheiro de Alimentos
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Prof. Alcinéia de L. S. Ramos
        ///Telefone: (35) 2142-2113
        ///E-mail: alcineia @ dca.ufla.br.
        /// </summary>
        internal static string Alimentos {
            get {
                return ResourceManager.GetString("Alimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Ronaldo Fia
        ///Telefone: (35) 3829-1028
        ///E-mail: ronaldofia@deg.ufla.br.
        /// </summary>
        internal static string Ambiental {
            get {
                return ResourceManager.GetString("Ambiental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Daniel Augusto Pereira
        ///Telefone: (35) 2142-2072
        ///E-mail: danielpereira@deg.ufla.br.
        /// </summary>
        internal static string Automacao {
            get {
                return ResourceManager.GetString("Automacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidades: Bacharelado
        ///Titulação: Bacharel em Ciências Biológicas
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 25 (para cada modalidade)
        ///Coordenador: Prof. Marconi Souza Silva
        ///Telefone: (35) 3829-3136
        ///E-mail: marconisilva @ dbi.ufla.br.
        /// </summary>
        internal static string BioBach {
            get {
                return ResourceManager.GetString("BioBach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidades: Licenciatura Presencial
        ///Titulação: Licenciado em Ciências Biológicas
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 25
        ///Coordenador: Profª Alessandra Angélica de Pádua Bueno
        ///Telefone: (35) 3829-1344
        ///E-mail: alebueno @ dbi.ufla.br.
        /// </summary>
        internal static string BioLicen {
            get {
                return ResourceManager.GetString("BioLicen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Ciência da Computação
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 40
        ///Coordenador: Profª. Marluce Rodrigues Pereira
        ///Telefone: (35) 3829-1540
        ///E-mail:  marluce@dcc.ufla.br.
        /// </summary>
        internal static string Computacao {
            get {
                return ResourceManager.GetString("Computacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Direito
        ///Regime: Semestral
        ///Período: Prioritariamente Noturno
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 60
        ///Coordenador: Prof. Pedro Ivo Ribeiro Diniz
        ///Telefone: (35) 3829-1950
        ///E-mail: pedrodiniz @ dae.ufla.br.
        /// </summary>
        internal static string Direito {
            get {
                return ResourceManager.GetString("Direito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade:Licenciatura
        ///Titulação: Licenciado em Filosofia
        ///Regime: Semestral
        ///Período: Noturno
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Prof. Luiz Marcos da Silva Filho
        ///Telefone: (35) 2142-2122
        ///E-mail: luizmarcos @ dch.ufla.br.
        /// </summary>
        internal static string Filosofia {
            get {
                return ResourceManager.GetString("Filosofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Licenciatura
        ///Titulação: Licenciado em Física
        ///Regime: Semestral
        ///Período: Noturno
        ///Duração: 9 semestres
        ///Nº de vagas por semestre: 30
        ///Coordenador: Prof. Gilberto Lage
        ///Telefone: (35) 3829-1380
        ///E-mail: glage @ dex.ufla.br.
        /// </summary>
        internal static string Fisica {
            get {
                return ResourceManager.GetString("Fisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Engenheiro Florestal
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenadora: Prof. Luis Antônio Coimbra Borges
        ///Telefone: (35) 3829-1063
        ///E-mail: luis.borges @ dcf.ufla.br.
        /// </summary>
        internal static string Florestal {
            get {
                return ResourceManager.GetString("Florestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Licenciatura
        ///Titulação: Licenciado em Letras
        ///Duração: 8 semestres
        ///Período: Noturno
        ///Nº de vagas por semestre: 50 vagas
        ///Coordenadora: Profª. Helena Maria Ferreira
        ///Telefone: (35) 2142-2110
        ///E-mail: helenaferreira @ dch.ufla.br.
        /// </summary>
        internal static string Letras {
            get {
                return ResourceManager.GetString("Letras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Licenciatura
        ///Titulação: Licenciado em Matemática
        ///Regime: Semestral
        ///Período: Noturno
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 30
        ///Coordenador: Profª. Amanda Castro Oliveira
        ///Telefone: (35) 3829-1511
        ///E-mail: amanda @ dex.ufla.br.
        /// </summary>
        internal static string Matematica {
            get {
                return ResourceManager.GetString("Matematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Médico
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 12 semestres
        ///Nº de vagas por semestre: 30
        ///Coordenadora: Profª. Luciano José Pereira
        ///Telefone: (35) 3829-5211
        ///E-mail: lucianojosepereira@dmv.ufla.br.
        /// </summary>
        internal static string Medicina {
            get {
                return ResourceManager.GetString("Medicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Nutrição
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 9 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Profª. Sandra Bragança Coelho
        ///Telefone: (35) 3829-5243
        ///E-mail: sandracoelho @ dca.ufla.br.
        /// </summary>
        internal static string Nutricao {
            get {
                return ResourceManager.GetString("Nutricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidades: Licenciatura e Bacharelado
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 25
        ///Coordenador: Prof. Jonas Leal Neto
        ///Telefone: (35) 3829-1515
        ///E-mail: neto.jl @ dqi.ufla.br.
        /// </summary>
        internal static string Quimica {
            get {
                return ResourceManager.GetString("Quimica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Sistemas de Informação
        ///Regime: Semestral
        ///Período: Noturno
        ///Duração: 8 semestres
        ///Nº de vagas por semestre: 40
        ///Coordenador: Profª. Ana Paula Piovesan Melchiori
        ///Telefone: (35) 3829-1935
        ///E-mail: anapaula @ dcc.ufla.br.
        /// </summary>
        internal static string Sistemas {
            get {
                return ResourceManager.GetString("Sistemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Medicina Veterinária
        ///Regime: Semestral
        ///Período: Integral
        ///Duração: 10 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenadora: Profª. Suely de Fátima Costa
        ///Telefone: (35) 3829-1740
        ///E-mail: sfcosta @ dmv.ufla.br.
        /// </summary>
        internal static string Veterinaria {
            get {
                return ResourceManager.GetString("Veterinaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade: Bacharelado
        ///Titulação: Bacharel em Zootecnia
        ///Período: Integral
        ///Regime: Semestral
        ///Duração: 9 semestres
        ///Nº de vagas por semestre: 50
        ///Coordenador: Prof. Edison José Fassani
        ///Telefone: (35) 3829-1067
        ///E-mail: fassani @ dzo.ufla.br.
        /// </summary>
        internal static string Zootecnia {
            get {
                return ResourceManager.GetString("Zootecnia", resourceCulture);
            }
        }
    }
}
